version: '3.9'

x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  backend:
    << : *restart_policy
    build:
      context: .
      dockerfile: Dockerfile
    # command: >-
    #   sh -c "
    #     npm i --only=dev
    #     && npm run dev
    #   "
    container_name: backend
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./aadhaarPrivate.json:/app/aadhaarPrivate.json
    ports:
      - "${PORT:-8000}:${PORT:-8000}"

  mongo:
    << : *restart_policy
    image: mongo:5.0.9
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME:-mongo_u}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-mongo_p}
      - MONGO_INITDB_DATABASE=${DB_DBNAME:-mongo_db}
    volumes:
      - ./db-data:/data/db
    expose:
      - 27017

  mongo-express:
    << : *restart_policy
    image: mongo-express
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME:-mongo_u}:${DB_PASSWORD:-mongo_p}@mongo:27017/
    ports:
      - 8081:8081
